# Generated by Django 3.2.3 on 2021-05-26 23:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoId', models.CharField(max_length=30, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.URLField()),
                ('description', models.CharField(max_length=250)),
                ('channelTitle', models.CharField(max_length=30)),
                ('isFavorite', models.BooleanField(default=False)),
            ],
        ),
    ]
